/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.1   2017-03-10

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

#include "mcu.h"

int main(void)
{
    char arr[9]="roosbeh\r\n";
    int i=0;
	SIM->SCGC5 |= 1UL<<10;                // Enable the clk on PORTB
	SIM->SOPT5 &= ~0xF;                   // Ensure the source for the UART 0 tx and Rx data is UART0 pins only
    SIM->SCGC4 |= 1UL<<10;                // Enable the clk on UART0

	PORTB->PCR[17] |= 1UL<<8 | 1UL<<9;    //ALT3 as UART0 Tx
	PORTB->PCR[16] |= 1UL<<8 | 1UL<<9;    //ALT3 as UART0 Rx


	UART0->C2 = 0;                        //~(1<<2 | 1<<3);      Both tx and Rx OFF
    UART0->BDH = 0x03;
	UART0->BDL = 0x0D;
                                          //Baud rate 9600
    UART0->C4  = 0x8;                     // BRFA value 01000 for 0.25 BRFD
    UART0->C1 = 0;                        // normal opt, no parity, (stopbit+8bit data+startbit) frame mode

    UART0->PFIFO = 0x80;                  //Tx FIFO enabled,Rx FIFO disable
    UART0->C2 = (1<<2 | 1<<3);      // Both tx and Rx ON

 /*  chnage the system clk to 120MHz   */

	while(1)
	{

        if(  ((UART0->S1 & 1UL<<7) != 0) &&    ((UART0->S1 & 1UL<<6) != 0)   )
        {
           UART0->D = arr[i];
           i++;
        }
        if(i==9)
        {
        	i=0;
        }

	}

}
