/*
******************************************************************************
File:     startup_MK64F12.s
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.1   2017-03-18

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

  .syntax unified
  .cpu cortex-m4
  .fpu softvfp
  .thumb

.global Reset_Handler
.global InterruptVector
.global Default_Handler

/* Linker script definitions */
/* start address for the initialization values of the .data section */
.word _sidata
/* start address for the .data section */
.word _sdata
/* end address for the .data section */
.word _edata
/* start address for the .bss section */
.word _sbss
/* end address for the .bss section */
.word _ebss


/**
**===========================================================================
**  Program - Reset_Handler
**  Abstract: This code gets called after reset.
**===========================================================================
*/
  .section  .text.Reset_Handler,"ax", %progbits
  .type Reset_Handler, %function
Reset_Handler:
  /* Set stack pointer */
  ldr sp,=_estack

  /* Branch to SystemInit function */
  bl SystemInit

  /* Copy data initialization values */
  ldr r1,=_sidata
  ldr r2,=_sdata
  ldr r3,=_edata
  b cmpdata
CopyLoop:
  ldr r0, [r1], #4
  str r0, [r2], #4
cmpdata:
  cmp r2, r3
  blt CopyLoop

  /* Clear BSS section */
  movs r0, #0
  ldr r2,=_sbss
  ldr r3,=_ebss
  b cmpbss
ClearLoop:
  str r0, [r2], #4
cmpbss:
  cmp r2, r3
  blt ClearLoop

  /* Call static constructors */
  bl __libc_init_array

  /* Branch to main */
  bl main

  /* If main returns, branch to Default_Handler. */
  b Default_Handler

  .size  Reset_Handler, .-Reset_Handler

/**
**===========================================================================
**  Program - Default_Handler
**  Abstract: This code gets called when the processor receives an
**    unexpected interrupt.
**===========================================================================
*/
  .section  .text.Default_Handler,"ax", %progbits
Default_Handler:
  b  Default_Handler

  .size  Default_Handler, .-Default_Handler

/**
**===========================================================================
**  Interrupt vector table
**===========================================================================
*/
  .section .isr_vector,"a", %progbits
InterruptVector:
  .word _estack                   /* 0 - Stack pointer */
  .word Reset_Handler             /* 1 - Reset */
  .word NMI_Handler               /* 2 - NMI  */
  .word HardFault_Handler         /* 3 - Hard fault */
  .word MemManage_Handler         /* 4 - Memory management fault */
  .word BusFault_Handler          /* 5 - Bus fault */
  .word UsageFault_Handler        /* 6 - Usage fault */
  .word 0                         /* 7 - Reserved */
  .word 0                         /* 8 - Reserved */
  .word 0                         /* 9 - Reserved */
  .word 0                         /* 10 - Reserved */
  .word SVC_Handler               /* 11 - SVCall */
  .word DebugMonitor_Handler      /* 12 - Reserved for Debug */
  .word 0                         /* 13 - Reserved */
  .word PendSV_Handler            /* 14 - PendSV */
  .word SysTick_Handler           /* 15 - Systick */

  /* External Interrupts */
  .word DMA0_IRQHandler           /* DMA Channel 0 Transfer Complete */
  .word DMA1_IRQHandler           /* DMA Channel 1 Transfer Complete */
  .word DMA2_IRQHandler           /* DMA Channel 2 Transfer Complete */
  .word DMA3_IRQHandler           /* DMA Channel 3 Transfer Complete */
  .word DMA4_IRQHandler           /* DMA Channel 4 Transfer Complete */
  .word DMA5_IRQHandler           /* DMA Channel 5 Transfer Complete */
  .word DMA6_IRQHandler           /* DMA Channel 6 Transfer Complete */
  .word DMA7_IRQHandler           /* DMA Channel 7 Transfer Complete */
  .word DMA8_IRQHandler           /* DMA Channel 8 Transfer Complete */
  .word DMA9_IRQHandler           /* DMA Channel 9 Transfer Complete */
  .word DMA10_IRQHandler          /* DMA Channel 10 Transfer Complete */
  .word DMA11_IRQHandler          /* DMA Channel 11 Transfer Complete */
  .word DMA12_IRQHandler          /* DMA Channel 12 Transfer Complete */
  .word DMA13_IRQHandler          /* DMA Channel 13 Transfer Complete */
  .word DMA14_IRQHandler          /* DMA Channel 14 Transfer Complete */
  .word DMA15_IRQHandler          /* DMA Channel 15 Transfer Complete */
  .word DMA_Error_IRQHandler      /* DMA Error Interrupt */
  .word MCM_IRQHandler            /* Normal Interrupt */
  .word FTFL_IRQHandler           /* FTFL Command complete interrupt */
  .word Read_Collision_IRQHandler /* Read Collision Interrupt */
  .word LVD_LVW_IRQHandler        /* Low Voltage Detect, Low Voltage Warning */
  .word LLW_IRQHandler            /* Low Leakage Wakeup */
  .word Watchdog_IRQHandler       /* WDOG Interrupt */
  .word RNG_IRQHandler            /* RNG Interrupt */
  .word I2C0_IRQHandler           /* I2C0 interrupt */
  .word I2C1_IRQHandler           /* I2C1 interrupt */
  .word SPI0_IRQHandler           /* SPI0 Interrupt */
  .word SPI1_IRQHandler           /* SPI1 Interrupt */
  .word I2S0_Tx_IRQHandler        /* I2S0 transmit interrupt */
  .word I2S0_Rx_IRQHandler        /* I2S0 receive interrupt */
  .word UART0_LON_IRQHandler      /* UART0 LON interrupt */
  .word UART0_RX_TX_IRQHandler    /* UART0 Receive/Transmit interrupt */
  .word UART0_ERR_IRQHandler      /* UART0 Error interrupt */
  .word UART1_RX_TX_IRQHandler    /* UART1 Receive/Transmit interrupt */
  .word UART1_ERR_IRQHandler      /* UART1 Error interrupt */
  .word UART2_RX_TX_IRQHandler    /* UART2 Receive/Transmit interrupt */
  .word UART2_ERR_IRQHandler      /* UART2 Error interrupt */
  .word UART3_RX_TX_IRQHandler    /* UART3 Receive/Transmit interrupt */
  .word UART3_ERR_IRQHandler      /* UART3 Error interrupt */
  .word ADC0_IRQHandler           /* ADC0 interrupt */
  .word CMP0_IRQHandler           /* CMP0 interrupt */
  .word CMP1_IRQHandler           /* CMP1 interrupt */
  .word FTM0_IRQHandler           /* FTM0 fault, overflow and channels interrupt */
  .word FTM1_IRQHandler           /* FTM1 fault, overflow and channels interrupt */
  .word FTM2_IRQHandler           /* FTM2 fault, overflow and channels interrupt */
  .word CMT_IRQHandler            /* CMT interrupt */
  .word RTC_IRQHandler            /* RTC interrupt */
  .word RTC_Seconds_IRQHandler    /* RTC seconds interrupt */
  .word PIT0_IRQHandler           /* PIT timer channel 0 interrupt */
  .word PIT1_IRQHandler           /* PIT timer channel 1 interrupt */
  .word PIT2_IRQHandler           /* PIT timer channel 2 interrupt */
  .word PIT3_IRQHandler           /* PIT timer channel 3 interrupt */
  .word PDB0_IRQHandler           /* PDB0 Interrupt */
  .word USB0_IRQHandler           /* USB0 interrupt */
  .word USBDCD_IRQHandler         /* USBDCD Interrupt */
  .word Reserved71_IRQHandler     /* Reserved interrupt 71 */
  .word DAC0_IRQHandler           /* DAC0 interrupt */
  .word MCG_IRQHandler            /* MCG Interrupt */
  .word LPTimer_IRQHandler        /* LPTimer interrupt */
  .word PORTA_IRQHandler          /* Port A interrupt */
  .word PORTB_IRQHandler          /* Port B interrupt */
  .word PORTC_IRQHandler          /* Port C interrupt */
  .word PORTD_IRQHandler          /* Port D interrupt */
  .word PORTE_IRQHandler          /* Port E interrupt */
  .word SWI_IRQHandler            /* Software interrupt */
  .word SPI2_IRQHandler           /* SPI2 Interrupt */
  .word UART4_RX_TX_IRQHandler    /* UART4 Receive/Transmit interrupt */
  .word UART4_ERR_IRQHandler      /* UART4 Error interrupt */
  .word UART5_RX_TX_IRQHandler    /* UART5 Receive/Transmit interrupt */
  .word UART5_ERR_IRQHandler      /* UART5 Error interrupt */
  .word CMP2_IRQHandler           /* CMP2 interrupt */
  .word FTM3_IRQHandler           /* FTM3 fault, overflow and channels interrupt */
  .word DAC1_IRQHandler           /* DAC1 interrupt */
  .word ADC1_IRQHandler           /* ADC1 interrupt */
  .word I2C2_IRQHandler           /* I2C2 interrupt */
  .word CAN0_ORed_Message_buffer_IRQHandler    /* CAN0 OR'd message buffers interrupt */
  .word CAN0_Bus_Off_IRQHandler      /* CAN0 bus off interrupt */
  .word CAN0_Error_IRQHandler        /* CAN0 error interrupt */
  .word CAN0_Tx_Warning_IRQHandler   /* CAN0 Tx warning interrupt */
  .word CAN0_Rx_Warning_IRQHandler   /* CAN0 Rx warning interrupt */
  .word CAN0_Wake_Up_IRQHandler      /* CAN0 wake up interrupt */
  .word SDHC_IRQHandler              /* SDHC interrupt */
  .word ENET_1588_Timer_IRQHandler   /* Ethernet MAC IEEE 1588 Timer Interrupt */
  .word ENET_Transmit_IRQHandler     /* Ethernet MAC Transmit Interrupt */
  .word ENET_Receive_IRQHandler      /* Ethernet MAC Receive Interrupt */
  .word ENET_Error_IRQHandler        /* Ethernet MAC Error and miscelaneous Interrupt */

/**
**===========================================================================
**  Flash configuration field
**===========================================================================
*/
.section .flash_cfg,"a", %progbits
FlashConfig:
  .word 0xffffffff     /* 0x400 Backdoor Comparison Key */
  .word 0xffffffff     /* 0x404 Backdoor Comparison Key */
  .word 0xffffffff     
  .word 0xfffffffe     


/**
**===========================================================================
**  Weak interrupt handlers redirected to Default_Handler. These can be
**  overridden in user code.
**===========================================================================
*/
  .weak NMI_Handler
  .thumb_set NMI_Handler, Default_Handler

  .weak HardFault_Handler
  .thumb_set HardFault_Handler, Default_Handler

  .weak MemManage_Handler
  .thumb_set MemManage_Handler, Default_Handler

  .weak BusFault_Handler
  .thumb_set BusFault_Handler, Default_Handler

  .weak UsageFault_Handler
  .thumb_set UsageFault_Handler, Default_Handler

  .weak SVC_Handler
  .thumb_set SVC_Handler, Default_Handler

  .weak DebugMonitor_Handler
  .thumb_set DebugMonitor_Handler, Default_Handler

  .weak PendSV_Handler
  .thumb_set PendSV_Handler, Default_Handler

  .weak SysTick_Handler
  .thumb_set SysTick_Handler, Default_Handler

  .weak DMA0_IRQHandler           
  .thumb_set DMA0_IRQHandler, Default_Handler           

  .weak DMA1_IRQHandler           
  .thumb_set DMA1_IRQHandler, Default_Handler           

  .weak DMA2_IRQHandler           
  .thumb_set DMA2_IRQHandler, Default_Handler           

  .weak DMA3_IRQHandler           
  .thumb_set DMA3_IRQHandler, Default_Handler           

  .weak DMA4_IRQHandler           
  .thumb_set DMA4_IRQHandler, Default_Handler           

  .weak DMA5_IRQHandler           
  .thumb_set DMA5_IRQHandler, Default_Handler           

  .weak DMA6_IRQHandler           
  .thumb_set DMA6_IRQHandler, Default_Handler           

  .weak DMA7_IRQHandler           
  .thumb_set DMA7_IRQHandler, Default_Handler           

  .weak DMA8_IRQHandler           
  .thumb_set DMA8_IRQHandler, Default_Handler           

  .weak DMA9_IRQHandler           
  .thumb_set DMA9_IRQHandler, Default_Handler           

  .weak DMA10_IRQHandler          
  .thumb_set DMA10_IRQHandler, Default_Handler          

  .weak DMA11_IRQHandler          
  .thumb_set DMA11_IRQHandler, Default_Handler          

  .weak DMA12_IRQHandler          
  .thumb_set DMA12_IRQHandler, Default_Handler          

  .weak DMA13_IRQHandler          
  .thumb_set DMA13_IRQHandler, Default_Handler          

  .weak DMA14_IRQHandler          
  .thumb_set DMA14_IRQHandler, Default_Handler          

  .weak DMA15_IRQHandler          
  .thumb_set DMA15_IRQHandler, Default_Handler          

  .weak DMA_Error_IRQHandler      
  .thumb_set DMA_Error_IRQHandler, Default_Handler      

  .weak MCM_IRQHandler            
  .thumb_set MCM_IRQHandler, Default_Handler            

  .weak FTFL_IRQHandler           
  .thumb_set FTFL_IRQHandler, Default_Handler           

  .weak Read_Collision_IRQHandler 
  .thumb_set Read_Collision_IRQHandler, Default_Handler 

  .weak LVD_LVW_IRQHandler        
  .thumb_set LVD_LVW_IRQHandler, Default_Handler        

  .weak LLW_IRQHandler            
  .thumb_set LLW_IRQHandler, Default_Handler            

  .weak Watchdog_IRQHandler       
  .thumb_set Watchdog_IRQHandler, Default_Handler       

  .weak RNG_IRQHandler            
  .thumb_set RNG_IRQHandler, Default_Handler            

  .weak I2C0_IRQHandler           
  .thumb_set I2C0_IRQHandler, Default_Handler           

  .weak I2C1_IRQHandler           
  .thumb_set I2C1_IRQHandler, Default_Handler           

  .weak SPI0_IRQHandler           
  .thumb_set SPI0_IRQHandler, Default_Handler           

  .weak SPI1_IRQHandler           
  .thumb_set SPI1_IRQHandler, Default_Handler           

  .weak I2S0_Tx_IRQHandler        
  .thumb_set I2S0_Tx_IRQHandler, Default_Handler        

  .weak I2S0_Rx_IRQHandler        
  .thumb_set I2S0_Rx_IRQHandler, Default_Handler        

  .weak UART0_LON_IRQHandler      
  .thumb_set UART0_LON_IRQHandler, Default_Handler      

  .weak UART0_RX_TX_IRQHandler    
  .thumb_set UART0_RX_TX_IRQHandler, Default_Handler    

  .weak UART0_ERR_IRQHandler      
  .thumb_set UART0_ERR_IRQHandler, Default_Handler      

  .weak UART1_RX_TX_IRQHandler    
  .thumb_set UART1_RX_TX_IRQHandler, Default_Handler    

  .weak UART1_ERR_IRQHandler      
  .thumb_set UART1_ERR_IRQHandler, Default_Handler      

  .weak UART2_RX_TX_IRQHandler    
  .thumb_set UART2_RX_TX_IRQHandler, Default_Handler    

  .weak UART2_ERR_IRQHandler      
  .thumb_set UART2_ERR_IRQHandler, Default_Handler      

  .weak UART3_RX_TX_IRQHandler    
  .thumb_set UART3_RX_TX_IRQHandler, Default_Handler    

  .weak UART3_ERR_IRQHandler      
  .thumb_set UART3_ERR_IRQHandler, Default_Handler      

  .weak ADC0_IRQHandler           
  .thumb_set ADC0_IRQHandler, Default_Handler           

  .weak CMP0_IRQHandler           
  .thumb_set CMP0_IRQHandler, Default_Handler           

  .weak CMP1_IRQHandler           
  .thumb_set CMP1_IRQHandler, Default_Handler           

  .weak FTM0_IRQHandler           
  .thumb_set FTM0_IRQHandler, Default_Handler           

  .weak FTM1_IRQHandler           
  .thumb_set FTM1_IRQHandler, Default_Handler           

  .weak FTM2_IRQHandler           
  .thumb_set FTM2_IRQHandler, Default_Handler           

  .weak CMT_IRQHandler            
  .thumb_set CMT_IRQHandler, Default_Handler            

  .weak RTC_IRQHandler            
  .thumb_set RTC_IRQHandler, Default_Handler            

  .weak RTC_Seconds_IRQHandler    
  .thumb_set RTC_Seconds_IRQHandler, Default_Handler    

  .weak PIT0_IRQHandler           
  .thumb_set PIT0_IRQHandler, Default_Handler           

  .weak PIT1_IRQHandler           
  .thumb_set PIT1_IRQHandler, Default_Handler           

  .weak PIT2_IRQHandler           
  .thumb_set PIT2_IRQHandler, Default_Handler           

  .weak PIT3_IRQHandler           
  .thumb_set PIT3_IRQHandler, Default_Handler           

  .weak PDB0_IRQHandler           
  .thumb_set PDB0_IRQHandler, Default_Handler           

  .weak USB0_IRQHandler           
  .thumb_set USB0_IRQHandler, Default_Handler           

  .weak USBDCD_IRQHandler         
  .thumb_set USBDCD_IRQHandler, Default_Handler         

  .weak Reserved71_IRQHandler     
  .thumb_set Reserved71_IRQHandler, Default_Handler     

  .weak DAC0_IRQHandler           
  .thumb_set DAC0_IRQHandler, Default_Handler           

  .weak MCG_IRQHandler            
  .thumb_set MCG_IRQHandler, Default_Handler            

  .weak LPTimer_IRQHandler        
  .thumb_set LPTimer_IRQHandler, Default_Handler        

  .weak PORTA_IRQHandler          
  .thumb_set PORTA_IRQHandler, Default_Handler          

  .weak PORTB_IRQHandler          
  .thumb_set PORTB_IRQHandler, Default_Handler          

  .weak PORTC_IRQHandler          
  .thumb_set PORTC_IRQHandler, Default_Handler          

  .weak PORTD_IRQHandler          
  .thumb_set PORTD_IRQHandler, Default_Handler          

  .weak PORTE_IRQHandler          
  .thumb_set PORTE_IRQHandler, Default_Handler          

  .weak SWI_IRQHandler            
  .thumb_set SWI_IRQHandler, Default_Handler            

  .weak SPI2_IRQHandler           
  .thumb_set SPI2_IRQHandler, Default_Handler           

  .weak UART4_RX_TX_IRQHandler    
  .thumb_set UART4_RX_TX_IRQHandler, Default_Handler    

  .weak UART4_ERR_IRQHandler      
  .thumb_set UART4_ERR_IRQHandler, Default_Handler      

  .weak UART5_RX_TX_IRQHandler    
  .thumb_set UART5_RX_TX_IRQHandler, Default_Handler    

  .weak UART5_ERR_IRQHandler      
  .thumb_set UART5_ERR_IRQHandler, Default_Handler      

  .weak CMP2_IRQHandler           
  .thumb_set CMP2_IRQHandler, Default_Handler           

  .weak FTM3_IRQHandler           
  .thumb_set FTM3_IRQHandler, Default_Handler           

  .weak DAC1_IRQHandler           
  .thumb_set DAC1_IRQHandler, Default_Handler           

  .weak ADC1_IRQHandler           
  .thumb_set ADC1_IRQHandler, Default_Handler           

  .weak I2C2_IRQHandler           
  .thumb_set I2C2_IRQHandler, Default_Handler           

  .weak CAN0_ORed_Message_buffer_IRQHandler
  .thumb_set CAN0_ORed_Message_buffer_IRQHandler, Default_Handler

  .weak CAN0_Bus_Off_IRQHandler   
  .thumb_set CAN0_Bus_Off_IRQHandler, Default_Handler   

  .weak CAN0_Error_IRQHandler     
  .thumb_set CAN0_Error_IRQHandler, Default_Handler     

  .weak CAN0_Tx_Warning_IRQHandler
  .thumb_set CAN0_Tx_Warning_IRQHandler, Default_Handler

  .weak CAN0_Rx_Warning_IRQHandler
  .thumb_set CAN0_Rx_Warning_IRQHandler, Default_Handler

  .weak CAN0_Wake_Up_IRQHandler   
  .thumb_set CAN0_Wake_Up_IRQHandler, Default_Handler   

  .weak SDHC_IRQHandler           
  .thumb_set SDHC_IRQHandler, Default_Handler           

  .weak ENET_1588_Timer_IRQHandler     
  .thumb_set ENET_1588_Timer_IRQHandler, Default_Handler     

  .weak ENET_Transmit_IRQHandler     
  .thumb_set ENET_Transmit_IRQHandler, Default_Handler     

  .weak ENET_Receive_IRQHandler     
  .thumb_set ENET_Receive_IRQHandler, Default_Handler     

  .weak ENET_Error_IRQHandler     
  .thumb_set ENET_Error_IRQHandler, Default_Handler     
  
  .end
  
